name: AshsEnchanting
main: com.example.ashsenchanting.AshsEnchanting
version: 1.0.7
api-version: '1.21'
description: Removes anvil Too Expensive restriction and allows Infinity+Mending coexistence.
author: Ash
