name: AshsEnchanting
main: com.example.ashsenchanting.AshsEnchanting
version: 1.0.9
api-version: '1.21'
description: Removes anvil Too Expensive restriction and allows Infinity+Mending coexistence.
author: Ash
commands:
  ashtetest:
    description: Gives an operator-only test bow for Too Expensive bypass validation.
    usage: /ashtetest
